### ISSUE TITLE
Includes Exclamation point in Anchor when GitHub ignores it

### ISSUE THREAD

**Issue by codeblooded** [thlorenz/anchor-markdown-header#12]
Links break when the a tag is declared like

```
# Get it!
```

The anchor tag should be #get-it, but the library currently marks it #get-it!
GitHub README links are then broken

**Comment by thlorenz** [comment]
Do you mind providing a failing test in a PR?
I could then fix it quicker and/or have someone else have a go.

Thanks.

**Comment by thlorenz** [comment]
Fixed in latest version.
