### ISSUE TITLE
generating newline in header entries

### ISSUE THREAD

**Issue by fresheneesz** [thlorenz/anchor-markdown-header#19]
I'm getting markdown that looks like this:

```
](#changelog)
- [How to Contribute!
](#how-to-contribute)
- [License
](#license)
```

From a header that looks like this:

```
`blocks.js`
============
```

This seems to be happening to all my top level headers.

Related issue: https://github.com/thlorenz/doctoc/issues/56

**Comment by thlorenz** [comment]
Could you please push up a full example to github so we can trouble shoot?

**Comment by RyanZim** [comment]
@fresheneesz Is this still an issue for you? If not, please close this. If it is, please push up a full example to github so we can trouble shoot.

**Comment by fresheneesz** [comment]
Hey sorry, I lost track of this and just fixed my problem manually. I would have expected someone with the project already up to do a quick test and verify whether or not its easily reproducible. If its not easily reproducible, I'll look into specifically what caused my problem. This one shouldn't be hard to repro.

**Comment by RyanZim** [comment]
OK, I'll see if I get time.

**Comment by RyanZim** [comment]
@fresheneesz Sorry, can't reproduce.

> please push up a full example to github so we can trouble shoot.

**Comment by fresheneesz** [comment]
Looks like it works now. Thanks!
