### ISSUE TITLE
ignore ~ and $ in anchor's output

### ISSUE THREAD

**Issue by borisirota** [thlorenz/anchor-markdown-header#20]
Hey,

Github and Bitbucket anchors ignore `~` and `$` when it is part of the header, but the anchor module doesn't filter it in it's output.

Currently, I'm doing the following workaround:
```javascript
replace(/\[(.+)\]\((#.+)\)/g, function (match) {
    return anchor(match[1], 'github.com').replace(/(\(#.+)~(.+\))/, '$1$2').replace(/(\(#.*)\$(.*\))/, '$1$2');
})
```

Thanks !

**Comment by thlorenz** [comment]
You could fix this inside the anchor-markdown-header source directly.
PRs are welcome.

**Comment by fresheneesz** [comment]
+1 - was just coming here to report this

**Comment by borisirota** [comment]
@thlorenz The pull request is ready :)
