### ISSUE TITLE
Incorrect inclusion of `@` in links

### ISSUE THREAD

**Issue by ihaque** [thlorenz/anchor-markdown-header#22]
If a header name includes an `@, doctoc (using this library) includes that in the link, but GitHub's parser does not.

For example: `# Talk from foo @ bar` produces `#talk-from-foo-@-bar`, but should produce `#talk-from-foo--bar`. 

I'm not experienced enough with Node development to write and test a proper PR, but it looks to me like it should only require adding `@` to the list of characters to strip at https://github.com/thlorenz/anchor-markdown-header/blob/master/anchor-markdown-header.js#L23.

**Comment by thlorenz** [comment]
@ihaque you are absolutely correct and I do encourage you to take this opportunity for a first PR :)

Make sure to add a [failing test here](https://github.com/thlorenz/anchor-markdown-header/blob/master/test/anchor-markdown-header.js#L14) (that will pass after your change).

Thanks.

**Comment by thlorenz** [comment]
Waiting for PR
