### ISSUE TITLE
Bug For a header with special characters an invalid link is generated

### ISSUE THREAD

**Issue by robwe** [thlorenz/anchor-markdown-header#23]
For the header

```
# Größe
```

(which is a normal German word) the TOC entry

```
[Größe](#gr%C3%B6%C3%9Fe)
```

is generated in an UTF-8 encoded file, but GitHub expects it to be

```
[Größe](#gr-e)
```

See the Ruby regular expression in [named anchors](http://github.com/jch/html-pipeline/blob/master/lib/html/pipeline/toc_filter.rb) in point 4 at [GitHub Markup](http://github.com/github/markup) about how GitHub generates the anchors.

**Comment by thlorenz** [comment]
Thanks for your help finding the source.

The named anchor link does not include entire regex we need.
Where in the github markup page do they generate headers? Looks like they're using red-carpet. At any rate I looked through the github markup code and couldn't find anything related to anchors.

**Comment by robwe** [comment]
Well, regardless of how github really creates the anchor names, a good approximation for the TOC entries (or probably even the real thing) would be to replace all non-letter-or-number characters, i.e. everything that is not [a-zA-Z0-9], by a dash and replacing multiple consecutive dashes by just one dash.

**Comment by leipert** [comment]
Two parts are responsible for the anchor generation in github.

1. Redcarpet: [code here](https://github.com/vmg/redcarpet/blob/master/ext/redcarpet/html.c#L267-L296)
2. html-pipline: [code here](https://github.com/jch/html-pipeline/blob/master/lib/html/pipeline/toc_filter.rb#L26-L36)

The first strips ``` -&+$,/:;=?@"#{}|^~[]`\\*()%.!'``` and replaces them with a `-` and turns all letters to lowercase. Consecutive stripped characters are simplified to one `-`, as can be seen [here](https://github.com/vmg/redcarpet/blob/master/test/html_toc_render_test.rb#L49-L54).

The second removes all Oniguruma non-word characters (`[^[:word:]\- ]`) and replaces spaces ` ` with a dash `-`. It also lowercases the id.

If you want, I could implement this in an PR, as there exists [node-oniguruma](https://github.com/atom/node-oniguruma).

**Comment by dmolesUC3** [comment]
@leipert I've looked at the Redcarpet and html-pipeline code and they don't actually match GitHub's current behavior very well. If you look at [this doctoc test page](https://github.com/thlorenz/doctoc/wiki/Test-UTF-8-Blocks), for instance, you can see that high-Latin and non-Latin characters aren't stripped, they're escaped, and consecutive dashes aren't collapsed.

And just to make things more confusing, when I paste that Markdown source into a Gist, the Gist renderer doesn't escape the characters, it just passes them through as-is.

So maybe GitHub was using Redcarpet and html-pipeline at one point, but if they are now, they've modified them heavily and AFAICT not published the changes. It would be nice if they'd actually document what they do!

**Comment by mcornella** [comment]
This is not how it's rendered now in GitHub, the original percent-encoding works correctly now. I think this could be closed.

**Comment by AndrewSouthpaw** [comment]
Taking it on @mcornella 's authority, someone feel free to provide a counter example if they think the issue still exists.
